nng-sys: revamp features + discover system NNG (#16)
Previously, without `build-nng`, we just emitted
`cargo:rustc-link-lib=dylib=nng` and hoped for the best. This wasn't
great for anyone who already had NNG built elsewhere, such as from their
distro, from nix, or even from a local dev build of NNG that they might
be testing.

The new discovery logic implements a preference hierarchy of where to
pick up NNG from (when not using a vendored build, which remains the
default):

1. Explicit env vars (`NNG_DIR`, `NNG_LIB_DIR`+`NNG_INCLUDE_DIR`)
2. pkg-config (though nanomsg/nng#926, so this is to future-proof) / vcpkg
3. Platform-specific fallback paths ("-lnng and pray" or Homebrew on macOS)

Vendoring is still enabled through a feature and on by default. This is
mainly because NNG isn't _generally_ going to be installed on users
systems, unlike more widely used libraries like openssl or zlib.
Besides, NNG is fast and easy enough to build that it's not too much of
a problem in practice. However, to allow end users to force the use of a
system-wide NNG install, I've added support for the `NNG_NO_VENDOR`
environment variable to override that behavior. This matches the pattern
from openssl-sys (`OPENSSL_NO_VENDOR`) and libgit2-sys
(`LIBGIT2_NO_VENDOR`), and is useful for deployments where deep control
over exact versions of dependencies are needed (e.g., in systems that
need to deal with compliance, SBOMs, etc.).

I've introduced another environment variable, `NNG_STATIC`, which can be
set to force either static or dynamic linking of NNG, but that one is
less interesting. There's also a `static` feature to request static
linking specifically (which would only be relevant when not using
vendored, where static is the default).

To be consistent with the rest of the Rust -sys ecosystem, I've renamed
the `build-nng` feature to just `vendored` (like libsqlite3-sys and
openssl-sys). Similarly, I flipped no_std to be an opt-in (and on by
default) `std` feature; this is needed to make the feature additive,
plus
<https://www.reddit.com/r/rust/comments/1hs6spy/psa_for_std_feature_in_no_std_libraries/>.

I've also renamed some of the other features:

- build-bindgen → bindgen, since we're not "building" bindgen
- nng-stats → vendored-stats, since it only affects vendored CMake build
- nng-* → * without the prefix, since it's implied that this is for nng

One important and more subtle change is that we now always re-generate
the bindings when using the system-provided NNG, since there is no
guarantee that it is the same version (or built with the same features)
as the pre-generated bindings. Vendored builds continue using
pre-generated bindings (unless the `bindgen` feature is enabled
explicitly or implicitly). In addition, I've added a CI job that checks
that the checked-in bindings are up to date.

diff --git a/.github/workflows/build-configurations.yml b/.github/workflows/build-configurations.yml
--- a/.github/workflows/build-configurations.yml
+++ b/.github/workflows/build-configurations.yml
@@ -17,45 +17,45 @@ jobs:
       matrix:
         include:
           - name: system + bindgen
-            features: build-bindgen
+            features: # no-default-features, so this won't vendor, and system implies bindgen
             # system nng, clang-dev for bindgen
             apt: libnng1 libnng-dev libclang-dev
             env: {}
           - name: vendored + bindgen
-            features: build-nng,build-bindgen
+            features: --features vendored,bindgen
             # vendored nng and clang-dev for bindgen
             apt: clang cmake libclang-dev
             env: {}
           - name: vendored + bundled
-            features: build-nng
+            features: --features vendored
             # vendored nng with bundled bindings, default generator (Unix Makefiles)
             apt: clang cmake
             env: {}
           - name: vendored with Ninja + bundled
-            features: build-nng
+            features: --features vendored
             # vendored nng with bundled bindings, ninja generator
             apt: clang cmake ninja-build
             env:
               CMAKE_GENERATOR: Ninja
           - name: vendored with stats + bundled
-            features: nng-stats
-            # vendored nng to get stats, bundled bindings.
+            features: --features vendored,vendored-stats
+            # vendored nng to get stats, bundled bindings
             apt: clang cmake
             env: {}
           - name: vendored with tls + bundled
-            features: nng-tls
+            features: --features vendored,tls
             # vendored nng to guarantee we get tls, bundled bindings, need to
             # link against mbedtls.
             apt: clang cmake libmbedtls-dev
             env: {}
           - name: vendored with compat (bindgen implied)
-            features: nng-compat
+            features: --features compat
             # to generate compat, we need to run bindgen since bundled do not
-            # include compat. use system nng though.
+            # include compat. bindgen feature is implied by compat.
             apt: libnng1 libnng-dev libclang-dev
             env: {}
           - name: vendored with supplemental (bindgen implied)
-            features: nng-supplemental
+            features: --features supplemental
             # ditto for supplemental
             apt: libnng1 libnng-dev libclang-dev
             env: {}
@@ -70,11 +70,11 @@ jobs:
         uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # branch=master
         with:
           toolchain: stable
-      - name: cargo test -p nng-sys --no-default-features --features ${{ matrix.features }}
-        run: cargo test -p nng-sys --locked --all-targets --no-default-features --features ${{ matrix.features }}
+      - name: cargo test -p nng-sys --no-default-features ${{ matrix.features }}
+        run: cargo test -p nng-sys --locked --all-targets --no-default-features ${{ matrix.features }}
         env: ${{ matrix.env }}
   linux-nng:
-    name: nng on linux without build-nng or build-bindgen
+    name: nng on linux / not vendored or bindgen
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # tag=v5.0.0
@@ -89,17 +89,50 @@ jobs:
           toolchain: stable
       - name: cargo test -p nng --no-default-features
         run: cargo test -p nng --locked --all-targets --no-default-features
+        env:
+          NNG_NO_VENDOR: "1"
+  linux-force-no-vendor:
+    name: nng on linux / NNG_NO_VENDOR
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # tag=v5.0.0
+        with:
+          submodules: true
+      # we test this by not installing nng, and checking that building _fails_
+      - name: Install stable
+        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # branch=master
+        with:
+          toolchain: stable
+      - name: cargo build -p nng-sys --features vendored
+        run: |
+          if cargo build -p nng-sys --locked --features vendored 2>&1; then
+            echo "Build should have failed with NNG_NO_VENDOR=1"
+            exit 1
+          fi
+          echo "Build correctly failed when NNG_NO_VENDOR is set"
+        env:
+          NNG_NO_VENDOR: "1"
   macos-sys:
-    name: nng-sys on macOS ${{ matrix.features }}
+    name: nng-sys on macOS / ${{ matrix.name }}
     runs-on: macos-latest
     strategy:
       fail-fast: false
       matrix:
         include:
-          - features:
+          - name: brew-provided nng + CFLAGS
+            features:
             brew: nng
-          - features: --features build-nng
+            env:
+              CFLAGS: -I/opt/homebrew/include
+              RUSTFLAGS: -L native=/opt/homebrew/lib
+          - name: brew-provided nng
+            features:
+            brew: nng
+            env: {}
+          - name: vendored
+            features: --features vendored
             brew: cmake
+            env: {}
     steps:
       - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # tag=v5.0.0
         with:
@@ -112,11 +145,8 @@ jobs:
         with:
           toolchain: stable
       - name: cargo test -p nng-sys --no-default-features ${{ matrix.features }}
-        run: |
-          env \
-            CFLAGS="-I$(brew --prefix)/include${CFLAGS+ ${CFLAGS}}" \
-            RUSTFLAGS="-L native=$(brew --prefix)/lib" \
-            cargo test -p nng-sys --locked --all-targets --no-default-features ${{ matrix.features }}
+        run: cargo test -p nng-sys --locked --all-targets --no-default-features ${{ matrix.features }}
+        env: ${{ matrix.env }}
   win-sys:
     name: nng-sys on Windows ${{ matrix.features }}
     runs-on: ${{ matrix.os }}
@@ -129,11 +159,11 @@ jobs:
           #   features:
           #   choco: libnng-dev
           - os: windows-2022
-            features: --features build-nng
+            features: --features vendored
             choco: llvm cmake
           # chocolatey cmake (4.1.2) doesn't have VS2026 yet (landed in 4.2)
           # - os: windows-2025
-          #   features: --features build-nng
+          #   features: --features vendored
           #   choco: llvm cmake
     steps:
       - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # tag=v5.0.0
